/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package consulo.platform.remote.agent.protocol;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class SystemInfo implements org.apache.thrift.TBase<SystemInfo, SystemInfo._Fields>, java.io.Serializable, Cloneable, Comparable<SystemInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SystemInfo");

  private static final org.apache.thrift.protocol.TField OS_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("osName", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField OS_VERSION_FIELD_DESC = new org.apache.thrift.protocol.TField("osVersion", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField ARCH_FIELD_DESC = new org.apache.thrift.protocol.TField("arch", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField HOSTNAME_FIELD_DESC = new org.apache.thrift.protocol.TField("hostname", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField CPU_COUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("cpuCount", org.apache.thrift.protocol.TType.I32, (short)5);
  private static final org.apache.thrift.protocol.TField TOTAL_MEMORY_FIELD_DESC = new org.apache.thrift.protocol.TField("totalMemory", org.apache.thrift.protocol.TType.I64, (short)6);
  private static final org.apache.thrift.protocol.TField CONSOLE_ENCODING_FIELD_DESC = new org.apache.thrift.protocol.TField("consoleEncoding", org.apache.thrift.protocol.TType.STRING, (short)7);
  private static final org.apache.thrift.protocol.TField LOCALE_FIELD_DESC = new org.apache.thrift.protocol.TField("locale", org.apache.thrift.protocol.TType.STRING, (short)8);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new SystemInfoStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new SystemInfoTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String osName; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String osVersion; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String arch; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String hostname; // required
  public int cpuCount; // required
  public long totalMemory; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String consoleEncoding; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String locale; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    OS_NAME((short)1, "osName"),
    OS_VERSION((short)2, "osVersion"),
    ARCH((short)3, "arch"),
    HOSTNAME((short)4, "hostname"),
    CPU_COUNT((short)5, "cpuCount"),
    TOTAL_MEMORY((short)6, "totalMemory"),
    CONSOLE_ENCODING((short)7, "consoleEncoding"),
    LOCALE((short)8, "locale");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // OS_NAME
          return OS_NAME;
        case 2: // OS_VERSION
          return OS_VERSION;
        case 3: // ARCH
          return ARCH;
        case 4: // HOSTNAME
          return HOSTNAME;
        case 5: // CPU_COUNT
          return CPU_COUNT;
        case 6: // TOTAL_MEMORY
          return TOTAL_MEMORY;
        case 7: // CONSOLE_ENCODING
          return CONSOLE_ENCODING;
        case 8: // LOCALE
          return LOCALE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __CPUCOUNT_ISSET_ID = 0;
  private static final int __TOTALMEMORY_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.OS_NAME, new org.apache.thrift.meta_data.FieldMetaData("osName", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.OS_VERSION, new org.apache.thrift.meta_data.FieldMetaData("osVersion", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ARCH, new org.apache.thrift.meta_data.FieldMetaData("arch", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.HOSTNAME, new org.apache.thrift.meta_data.FieldMetaData("hostname", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CPU_COUNT, new org.apache.thrift.meta_data.FieldMetaData("cpuCount", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.TOTAL_MEMORY, new org.apache.thrift.meta_data.FieldMetaData("totalMemory", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.CONSOLE_ENCODING, new org.apache.thrift.meta_data.FieldMetaData("consoleEncoding", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.LOCALE, new org.apache.thrift.meta_data.FieldMetaData("locale", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SystemInfo.class, metaDataMap);
  }

  public SystemInfo() {
  }

  public SystemInfo(
    java.lang.String osName,
    java.lang.String osVersion,
    java.lang.String arch,
    java.lang.String hostname,
    int cpuCount,
    long totalMemory,
    java.lang.String consoleEncoding,
    java.lang.String locale)
  {
    this();
    this.osName = osName;
    this.osVersion = osVersion;
    this.arch = arch;
    this.hostname = hostname;
    this.cpuCount = cpuCount;
    setCpuCountIsSet(true);
    this.totalMemory = totalMemory;
    setTotalMemoryIsSet(true);
    this.consoleEncoding = consoleEncoding;
    this.locale = locale;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SystemInfo(SystemInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetOsName()) {
      this.osName = other.osName;
    }
    if (other.isSetOsVersion()) {
      this.osVersion = other.osVersion;
    }
    if (other.isSetArch()) {
      this.arch = other.arch;
    }
    if (other.isSetHostname()) {
      this.hostname = other.hostname;
    }
    this.cpuCount = other.cpuCount;
    this.totalMemory = other.totalMemory;
    if (other.isSetConsoleEncoding()) {
      this.consoleEncoding = other.consoleEncoding;
    }
    if (other.isSetLocale()) {
      this.locale = other.locale;
    }
  }

  @Override
  public SystemInfo deepCopy() {
    return new SystemInfo(this);
  }

  @Override
  public void clear() {
    this.osName = null;
    this.osVersion = null;
    this.arch = null;
    this.hostname = null;
    setCpuCountIsSet(false);
    this.cpuCount = 0;
    setTotalMemoryIsSet(false);
    this.totalMemory = 0;
    this.consoleEncoding = null;
    this.locale = null;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getOsName() {
    return this.osName;
  }

  public SystemInfo setOsName(@org.apache.thrift.annotation.Nullable java.lang.String osName) {
    this.osName = osName;
    return this;
  }

  public void unsetOsName() {
    this.osName = null;
  }

  /** Returns true if field osName is set (has been assigned a value) and false otherwise */
  public boolean isSetOsName() {
    return this.osName != null;
  }

  public void setOsNameIsSet(boolean value) {
    if (!value) {
      this.osName = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getOsVersion() {
    return this.osVersion;
  }

  public SystemInfo setOsVersion(@org.apache.thrift.annotation.Nullable java.lang.String osVersion) {
    this.osVersion = osVersion;
    return this;
  }

  public void unsetOsVersion() {
    this.osVersion = null;
  }

  /** Returns true if field osVersion is set (has been assigned a value) and false otherwise */
  public boolean isSetOsVersion() {
    return this.osVersion != null;
  }

  public void setOsVersionIsSet(boolean value) {
    if (!value) {
      this.osVersion = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getArch() {
    return this.arch;
  }

  public SystemInfo setArch(@org.apache.thrift.annotation.Nullable java.lang.String arch) {
    this.arch = arch;
    return this;
  }

  public void unsetArch() {
    this.arch = null;
  }

  /** Returns true if field arch is set (has been assigned a value) and false otherwise */
  public boolean isSetArch() {
    return this.arch != null;
  }

  public void setArchIsSet(boolean value) {
    if (!value) {
      this.arch = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getHostname() {
    return this.hostname;
  }

  public SystemInfo setHostname(@org.apache.thrift.annotation.Nullable java.lang.String hostname) {
    this.hostname = hostname;
    return this;
  }

  public void unsetHostname() {
    this.hostname = null;
  }

  /** Returns true if field hostname is set (has been assigned a value) and false otherwise */
  public boolean isSetHostname() {
    return this.hostname != null;
  }

  public void setHostnameIsSet(boolean value) {
    if (!value) {
      this.hostname = null;
    }
  }

  public int getCpuCount() {
    return this.cpuCount;
  }

  public SystemInfo setCpuCount(int cpuCount) {
    this.cpuCount = cpuCount;
    setCpuCountIsSet(true);
    return this;
  }

  public void unsetCpuCount() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CPUCOUNT_ISSET_ID);
  }

  /** Returns true if field cpuCount is set (has been assigned a value) and false otherwise */
  public boolean isSetCpuCount() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CPUCOUNT_ISSET_ID);
  }

  public void setCpuCountIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CPUCOUNT_ISSET_ID, value);
  }

  public long getTotalMemory() {
    return this.totalMemory;
  }

  public SystemInfo setTotalMemory(long totalMemory) {
    this.totalMemory = totalMemory;
    setTotalMemoryIsSet(true);
    return this;
  }

  public void unsetTotalMemory() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __TOTALMEMORY_ISSET_ID);
  }

  /** Returns true if field totalMemory is set (has been assigned a value) and false otherwise */
  public boolean isSetTotalMemory() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __TOTALMEMORY_ISSET_ID);
  }

  public void setTotalMemoryIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __TOTALMEMORY_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getConsoleEncoding() {
    return this.consoleEncoding;
  }

  public SystemInfo setConsoleEncoding(@org.apache.thrift.annotation.Nullable java.lang.String consoleEncoding) {
    this.consoleEncoding = consoleEncoding;
    return this;
  }

  public void unsetConsoleEncoding() {
    this.consoleEncoding = null;
  }

  /** Returns true if field consoleEncoding is set (has been assigned a value) and false otherwise */
  public boolean isSetConsoleEncoding() {
    return this.consoleEncoding != null;
  }

  public void setConsoleEncodingIsSet(boolean value) {
    if (!value) {
      this.consoleEncoding = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getLocale() {
    return this.locale;
  }

  public SystemInfo setLocale(@org.apache.thrift.annotation.Nullable java.lang.String locale) {
    this.locale = locale;
    return this;
  }

  public void unsetLocale() {
    this.locale = null;
  }

  /** Returns true if field locale is set (has been assigned a value) and false otherwise */
  public boolean isSetLocale() {
    return this.locale != null;
  }

  public void setLocaleIsSet(boolean value) {
    if (!value) {
      this.locale = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case OS_NAME:
      if (value == null) {
        unsetOsName();
      } else {
        setOsName((java.lang.String)value);
      }
      break;

    case OS_VERSION:
      if (value == null) {
        unsetOsVersion();
      } else {
        setOsVersion((java.lang.String)value);
      }
      break;

    case ARCH:
      if (value == null) {
        unsetArch();
      } else {
        setArch((java.lang.String)value);
      }
      break;

    case HOSTNAME:
      if (value == null) {
        unsetHostname();
      } else {
        setHostname((java.lang.String)value);
      }
      break;

    case CPU_COUNT:
      if (value == null) {
        unsetCpuCount();
      } else {
        setCpuCount((java.lang.Integer)value);
      }
      break;

    case TOTAL_MEMORY:
      if (value == null) {
        unsetTotalMemory();
      } else {
        setTotalMemory((java.lang.Long)value);
      }
      break;

    case CONSOLE_ENCODING:
      if (value == null) {
        unsetConsoleEncoding();
      } else {
        setConsoleEncoding((java.lang.String)value);
      }
      break;

    case LOCALE:
      if (value == null) {
        unsetLocale();
      } else {
        setLocale((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case OS_NAME:
      return getOsName();

    case OS_VERSION:
      return getOsVersion();

    case ARCH:
      return getArch();

    case HOSTNAME:
      return getHostname();

    case CPU_COUNT:
      return getCpuCount();

    case TOTAL_MEMORY:
      return getTotalMemory();

    case CONSOLE_ENCODING:
      return getConsoleEncoding();

    case LOCALE:
      return getLocale();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case OS_NAME:
      return isSetOsName();
    case OS_VERSION:
      return isSetOsVersion();
    case ARCH:
      return isSetArch();
    case HOSTNAME:
      return isSetHostname();
    case CPU_COUNT:
      return isSetCpuCount();
    case TOTAL_MEMORY:
      return isSetTotalMemory();
    case CONSOLE_ENCODING:
      return isSetConsoleEncoding();
    case LOCALE:
      return isSetLocale();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof SystemInfo)
      return this.equals((SystemInfo)that);
    return false;
  }

  public boolean equals(SystemInfo that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_osName = true && this.isSetOsName();
    boolean that_present_osName = true && that.isSetOsName();
    if (this_present_osName || that_present_osName) {
      if (!(this_present_osName && that_present_osName))
        return false;
      if (!this.osName.equals(that.osName))
        return false;
    }

    boolean this_present_osVersion = true && this.isSetOsVersion();
    boolean that_present_osVersion = true && that.isSetOsVersion();
    if (this_present_osVersion || that_present_osVersion) {
      if (!(this_present_osVersion && that_present_osVersion))
        return false;
      if (!this.osVersion.equals(that.osVersion))
        return false;
    }

    boolean this_present_arch = true && this.isSetArch();
    boolean that_present_arch = true && that.isSetArch();
    if (this_present_arch || that_present_arch) {
      if (!(this_present_arch && that_present_arch))
        return false;
      if (!this.arch.equals(that.arch))
        return false;
    }

    boolean this_present_hostname = true && this.isSetHostname();
    boolean that_present_hostname = true && that.isSetHostname();
    if (this_present_hostname || that_present_hostname) {
      if (!(this_present_hostname && that_present_hostname))
        return false;
      if (!this.hostname.equals(that.hostname))
        return false;
    }

    boolean this_present_cpuCount = true;
    boolean that_present_cpuCount = true;
    if (this_present_cpuCount || that_present_cpuCount) {
      if (!(this_present_cpuCount && that_present_cpuCount))
        return false;
      if (this.cpuCount != that.cpuCount)
        return false;
    }

    boolean this_present_totalMemory = true;
    boolean that_present_totalMemory = true;
    if (this_present_totalMemory || that_present_totalMemory) {
      if (!(this_present_totalMemory && that_present_totalMemory))
        return false;
      if (this.totalMemory != that.totalMemory)
        return false;
    }

    boolean this_present_consoleEncoding = true && this.isSetConsoleEncoding();
    boolean that_present_consoleEncoding = true && that.isSetConsoleEncoding();
    if (this_present_consoleEncoding || that_present_consoleEncoding) {
      if (!(this_present_consoleEncoding && that_present_consoleEncoding))
        return false;
      if (!this.consoleEncoding.equals(that.consoleEncoding))
        return false;
    }

    boolean this_present_locale = true && this.isSetLocale();
    boolean that_present_locale = true && that.isSetLocale();
    if (this_present_locale || that_present_locale) {
      if (!(this_present_locale && that_present_locale))
        return false;
      if (!this.locale.equals(that.locale))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetOsName()) ? 131071 : 524287);
    if (isSetOsName())
      hashCode = hashCode * 8191 + osName.hashCode();

    hashCode = hashCode * 8191 + ((isSetOsVersion()) ? 131071 : 524287);
    if (isSetOsVersion())
      hashCode = hashCode * 8191 + osVersion.hashCode();

    hashCode = hashCode * 8191 + ((isSetArch()) ? 131071 : 524287);
    if (isSetArch())
      hashCode = hashCode * 8191 + arch.hashCode();

    hashCode = hashCode * 8191 + ((isSetHostname()) ? 131071 : 524287);
    if (isSetHostname())
      hashCode = hashCode * 8191 + hostname.hashCode();

    hashCode = hashCode * 8191 + cpuCount;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(totalMemory);

    hashCode = hashCode * 8191 + ((isSetConsoleEncoding()) ? 131071 : 524287);
    if (isSetConsoleEncoding())
      hashCode = hashCode * 8191 + consoleEncoding.hashCode();

    hashCode = hashCode * 8191 + ((isSetLocale()) ? 131071 : 524287);
    if (isSetLocale())
      hashCode = hashCode * 8191 + locale.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(SystemInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetOsName(), other.isSetOsName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOsName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.osName, other.osName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetOsVersion(), other.isSetOsVersion());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOsVersion()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.osVersion, other.osVersion);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetArch(), other.isSetArch());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetArch()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.arch, other.arch);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetHostname(), other.isSetHostname());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHostname()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.hostname, other.hostname);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetCpuCount(), other.isSetCpuCount());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCpuCount()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.cpuCount, other.cpuCount);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetTotalMemory(), other.isSetTotalMemory());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTotalMemory()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.totalMemory, other.totalMemory);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetConsoleEncoding(), other.isSetConsoleEncoding());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetConsoleEncoding()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.consoleEncoding, other.consoleEncoding);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetLocale(), other.isSetLocale());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLocale()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.locale, other.locale);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("SystemInfo(");
    boolean first = true;

    sb.append("osName:");
    if (this.osName == null) {
      sb.append("null");
    } else {
      sb.append(this.osName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("osVersion:");
    if (this.osVersion == null) {
      sb.append("null");
    } else {
      sb.append(this.osVersion);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("arch:");
    if (this.arch == null) {
      sb.append("null");
    } else {
      sb.append(this.arch);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("hostname:");
    if (this.hostname == null) {
      sb.append("null");
    } else {
      sb.append(this.hostname);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("cpuCount:");
    sb.append(this.cpuCount);
    first = false;
    if (!first) sb.append(", ");
    sb.append("totalMemory:");
    sb.append(this.totalMemory);
    first = false;
    if (!first) sb.append(", ");
    sb.append("consoleEncoding:");
    if (this.consoleEncoding == null) {
      sb.append("null");
    } else {
      sb.append(this.consoleEncoding);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("locale:");
    if (this.locale == null) {
      sb.append("null");
    } else {
      sb.append(this.locale);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (osName == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'osName' was not present! Struct: " + toString());
    }
    if (osVersion == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'osVersion' was not present! Struct: " + toString());
    }
    if (arch == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'arch' was not present! Struct: " + toString());
    }
    if (hostname == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'hostname' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'cpuCount' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'totalMemory' because it's a primitive and you chose the non-beans generator.
    if (consoleEncoding == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'consoleEncoding' was not present! Struct: " + toString());
    }
    if (locale == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'locale' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SystemInfoStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public SystemInfoStandardScheme getScheme() {
      return new SystemInfoStandardScheme();
    }
  }

  private static class SystemInfoStandardScheme extends org.apache.thrift.scheme.StandardScheme<SystemInfo> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, SystemInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // OS_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.osName = iprot.readString();
              struct.setOsNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // OS_VERSION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.osVersion = iprot.readString();
              struct.setOsVersionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // ARCH
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.arch = iprot.readString();
              struct.setArchIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // HOSTNAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.hostname = iprot.readString();
              struct.setHostnameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // CPU_COUNT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.cpuCount = iprot.readI32();
              struct.setCpuCountIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // TOTAL_MEMORY
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.totalMemory = iprot.readI64();
              struct.setTotalMemoryIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // CONSOLE_ENCODING
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.consoleEncoding = iprot.readString();
              struct.setConsoleEncodingIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // LOCALE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.locale = iprot.readString();
              struct.setLocaleIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetCpuCount()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'cpuCount' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetTotalMemory()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'totalMemory' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, SystemInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.osName != null) {
        oprot.writeFieldBegin(OS_NAME_FIELD_DESC);
        oprot.writeString(struct.osName);
        oprot.writeFieldEnd();
      }
      if (struct.osVersion != null) {
        oprot.writeFieldBegin(OS_VERSION_FIELD_DESC);
        oprot.writeString(struct.osVersion);
        oprot.writeFieldEnd();
      }
      if (struct.arch != null) {
        oprot.writeFieldBegin(ARCH_FIELD_DESC);
        oprot.writeString(struct.arch);
        oprot.writeFieldEnd();
      }
      if (struct.hostname != null) {
        oprot.writeFieldBegin(HOSTNAME_FIELD_DESC);
        oprot.writeString(struct.hostname);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(CPU_COUNT_FIELD_DESC);
      oprot.writeI32(struct.cpuCount);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(TOTAL_MEMORY_FIELD_DESC);
      oprot.writeI64(struct.totalMemory);
      oprot.writeFieldEnd();
      if (struct.consoleEncoding != null) {
        oprot.writeFieldBegin(CONSOLE_ENCODING_FIELD_DESC);
        oprot.writeString(struct.consoleEncoding);
        oprot.writeFieldEnd();
      }
      if (struct.locale != null) {
        oprot.writeFieldBegin(LOCALE_FIELD_DESC);
        oprot.writeString(struct.locale);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SystemInfoTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public SystemInfoTupleScheme getScheme() {
      return new SystemInfoTupleScheme();
    }
  }

  private static class SystemInfoTupleScheme extends org.apache.thrift.scheme.TupleScheme<SystemInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SystemInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeString(struct.osName);
      oprot.writeString(struct.osVersion);
      oprot.writeString(struct.arch);
      oprot.writeString(struct.hostname);
      oprot.writeI32(struct.cpuCount);
      oprot.writeI64(struct.totalMemory);
      oprot.writeString(struct.consoleEncoding);
      oprot.writeString(struct.locale);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SystemInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.osName = iprot.readString();
      struct.setOsNameIsSet(true);
      struct.osVersion = iprot.readString();
      struct.setOsVersionIsSet(true);
      struct.arch = iprot.readString();
      struct.setArchIsSet(true);
      struct.hostname = iprot.readString();
      struct.setHostnameIsSet(true);
      struct.cpuCount = iprot.readI32();
      struct.setCpuCountIsSet(true);
      struct.totalMemory = iprot.readI64();
      struct.setTotalMemoryIsSet(true);
      struct.consoleEncoding = iprot.readString();
      struct.setConsoleEncodingIsSet(true);
      struct.locale = iprot.readString();
      struct.setLocaleIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

